# Generated by Django 3.2.4 on 2023-07-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20230725_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='vote_total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
