# Generated by Django 3.2.4 on 2023-08-02 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created']},
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
