# Generated by Django 3.2.4 on 2023-08-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
